Added an rc.local file, to re-read the sysctl settings right after all normal services have been started, after boot.
konstruktoid/ansible-role-hardening pull request #340
Opened 2023-06-16 01:12 UTC by KoenDG

I was testing disabling ipv6 with a new set of Ubuntu 20 vms, and I noticed on reboot, the interfaces still had IPV6 addresses.

Checking sysctl, they had the settings I expected:

```
  net.ipv6.conf.all.disable_ipv6: 1
  net.ipv6.conf.default.disable_ipv6: 1
  net.ipv6.conf.lo.disable_ipv6: 1
```

Same with the grub configuration.

But, after every reboot, still had ipv6 addresses.

Googling around, I found that adding a file at `/etc/rc.local` could help.

I found this here: https://itsfoss.com/disable-ipv6-ubuntu-linux/

And some explanation here: https://unix.stackexchange.com/questions/49626/purpose-and-typical-usage-of-etc-rc-local

> The script /etc/rc.local is for use by the system administrator. It is traditionally executed after all the normal system services are started, at the end of the process of switching to a multiuser runlevel

Adding this file does consistently result in the interfaces not having an ipv6 address after reboot.

That being said, I find this quite strange. As the explanation says, you should almost never need `/etc/rc.local`. And it calling `/etc/init.d/procps restart` also seems antiquated, although I would have no way to know, it just feels that way.

I offer this PR as my solution, but it would be nice to see if the problem could be confirmed.

Like I said: all sysctl settings after reboot were as expected... but upon checking the interfaces, they had IPV6 addresses.

2023-06-16 05:43 UTC, konstruktoid commented
Hi again @KoenDG
I haven't seen this behaviour before, I'll look into it.

2023-06-26 18:33 UTC, KoenDG commented
Odd. I'll have a look and try again.

2023-08-07 09:31 UTC, konstruktoid requested changes
need to be verified

2023-08-07 18:44 UTC, KoenDG commented
I haven't had time for this and probably won't for a few weeks. Feel free to close if it's in the way.

2023-08-28 01:01 UTC, KoenDG commented
An update on this, I think I have an idea as to why this is happening:

My first hint was this ticket: https://bugs.launchpad.net/ubuntu/+source/procps/+bug/50093

Where it's described that the sysctl.d documentation points out this behavior. In there I find:


>Many sysctl parameters only become available when certain kernel
modules are loaded. Modules are usually loaded on demand, e.g.
when certain hardware is plugged in or network brought up. This
means that systemd-sysctl.service(8) which runs during early boot
**will not configure such parameters if they become available after
it has run**. To set such parameters, it is recommended to add an
udev(7) rule to set those parameters when they become available.
Alternatively, a slightly simpler and less efficient option is to
add the module to modules-load.d(5), causing it to be loaded
statically before sysctl settings are applied (see example
below).


In short: it looks like my network interface is added after sysctl settings are applied during boot. This somehow means they don't directly apply, because it's a "new" interface. I think that's what's happening, from what I'm reading.

Although I would expected the "all.disable_ipv6 = 1" to take care of that...

My VMs run on Virtualbox, on a Windows host. The windows host has a separate network card that I use. The VM network uses that as a bridge adapter.

This interface is simply defined by netplan:

```
# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      addresses:
      - 192.168.0.151/24
      nameservers:
        addresses:
        - 1.1.1.1
        search:
        - 1.1.1.1
      routes:
      - to: default
        via: 192.168.0.1
  version: 2
```

If I rename the interface and reboot, the VM boots without network. Going into the console, changing the name and doing a `sudo netplan apply` bring the interface up, with an IPV6 address.



Basically, this means that any interfaces that come up after the sysctl service has run early at boot, will not get the provided settings applied, and sysctl has to be run again to add them to all new interfaces.

2023-08-28 07:33 UTC, konstruktoid commented
Yeah, that seems to be an issue after reading about it.
But I wonder why the grub (https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/ipv6.yml#L5) settings aren't kicking in, can you run `grep "linux.*ipv6.disable=1" /boot/grub/grub.cfg`?

2023-08-28 20:45 UTC, KoenDG commented
You reference `/boot/grub/grub.cfg`, but that's a RedHat option. So, that's not there.

The Debian option, which you link, is present on the system:

```
koen@ubuntuservertestansiblehardening:~$  sudo cat /etc/default/grub.d/99-hardening-ipv6.cfg
[sudo] password for koen:
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX ipv6.disable=1"
```

Ok, I googled around about this after pasting the code bit up there, and found out what's happening.

I needed to run `sudo update-grub`.

I rebooted a few times without it, still had ipv6.

Then I ran `sudo update-grub` and all reboots after that, no ipv6.

So the question becomes: why didn't this run? There is a handler for it, but that only runs at the end of apparmor settings: https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/apparmor.yml#L14

There's also a bit of auditd code that sets the grub file but doesn't call update-grub: https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/auditd.yml#L6

There's also a separate invocation in `post.yml`: https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/post.yml#L59

It seems to me that the ipv6 code, and auditd code which seems to suffer a similar situation, require adding a call to that handler, I imagine that should address this situation.

Running the entire playbook means eventually you're reach the command in `post.yml`, which then functions as a catch-all for all the changes up to that point. But if you do only specific playbooks or tags, that gets skipped.

I'll test it and submit a new PR.

2023-08-28 21:05 UTC, KoenDG commented
Confirmed, separate PR made, closing this one.

2023-08-28 21:05 UTC, closed without merging

2023-08-29 07:31 UTC, konstruktoid commented
> You reference `/boot/grub/grub.cfg`, but that's a RedHat option. So, that's not there.

The this should fail: https://github.com/konstruktoid/ansible-role-hardening/blob/master/molecule/default/verify.yml#L518-L525

2023-08-29 09:20 UTC, KoenDG commented
> > You reference `/boot/grub/grub.cfg`, but that's a RedHat option. So, that's not there.
> 
> Then this should fail: https://github.com/konstruktoid/ansible-role-hardening/blob/master/molecule/default/verify.yml#L518-L525
> 
> ```shell
> $ lsb_release -d && grep generated /boot/grub/grub.cfg
> Description:	Ubuntu 22.04.3 LTS
> # It is automatically generated by grub-mkconfig using templates
> ```

Huh yeah it should. But the codebase only updates that file if the os is RedHat, the condition is right there in the code.

Unless it gets updated at some other point, I don't know the code by head fully so I couldn't say.

2023-08-30 12:31 UTC, KoenDG commented
Oh huh. That would have explained it too, yeah.

Ok, I was only going off what I was seeing in the ansible code.