Disable TCP Timestamp
konstruktoid/ansible-role-hardening pull request #387
Opened 2023-09-10 01:00 UTC by Acenl12

the TCP timestamp response to approximate the remote host's uptime and aid in further attacks. Additionally, some operating systems can be fingerprinted based on the behavior of their TCP time stamps.

2023-11-09 12:59 UTC, konstruktoid commented
Hi again @Acenl12 
Any updates?

2023-12-12 10:33 UTC, konstruktoid requested changes
Fix `ufw` change.

2023-12-12 10:33 UTC, konstruktoid commented on defaults/main/sysctl.yml
> +  net.ipv4.tcp_timestamps: 0
@Acenl12 thanks for the PR, but why disable instead of using the default  `1`?

2023-12-12 10:33 UTC, konstruktoid commented on defaults/main/ufw.yml
> +ufw_enable: false
This shouldn't be changed.

2023-12-12 10:35 UTC, closed without merging

2023-12-12 10:35 UTC, Acenl12 commented
Oops was a mistake