Fix template variable for task mount.yml
konstruktoid/ansible-role-hardening pull request #398
Opened 2023-09-28 17:13 UTC by cleberb

2023-09-29 12:21 UTC, konstruktoid requested changes
You'll need to add `tmp_mount_template: etc/systemd/tmp.mount.j2` to `defaults/main/templates.yml` as well

2023-09-29 12:21 UTC, konstruktoid commented
Thanks! I've added a review.

2023-09-29 22:28 UTC, cleberb commented
> You'll need to add `tmp_mount_template: etc/systemd/tmp.mount.j2` to `defaults/main/templates.yml` as well 

Fix.

2023-09-30 07:18 UTC, konstruktoid approved these changes

2023-09-30 07:18 UTC, merged