Unattended upgrades improvments
konstruktoid/ansible-role-hardening pull request #718
Opened 2024-08-23 19:08 UTC by jdaln

I had to postpone this a bit sorry.

This is a very early draft PR. Feel free to add commits. I will continue next week.

Relates to #699 .

2024-08-29 12:15 UTC, konstruktoid commented
> @konstruktoid Should the RedHat side be done in the same PR?
> 
> I can propose some code but I am currently not able to test it.

`dnf_automatic` doesn't have that many options, it just need to support https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/automatic_updates.yml#L42

https://dnf.readthedocs.io/en/latest/automatic.html

2024-08-29 12:29 UTC, jdaln commented
> > @konstruktoid Should the RedHat side be done in the same PR?
> > I can propose some code but I am currently not able to test it.
> 
> `dnf_automatic` doesn't have that many options, it just need to support https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/automatic_updates.yml#L42
> 
> https://dnf.readthedocs.io/en/latest/automatic.html
Alright, I mark this as ready. If this feature is wanted in the future, what could be done is something like this as a workaround:

```
- name: Configure reboot systemd service
      ansible.builtin.template:
        src: reboot-service.j2
        dest: /etc/systemd/system/reboot-if-needed.service
        mode: "0644"

    - name: Configure reboot systemd timer
      ansible.builtin.template:
        src: reboot-timer.j2
        dest: /etc/systemd/system/reboot-if-needed.timer
        mode: "0644"

    - name: Enable and start reboot timer
      ansible.builtin.systemd:
        name: reboot-if-needed.timer
        enabled: true
        state: started
```
with
reboot-service.j2

```
[Unit]
Description=Reboot the system if needed at a scheduled time

[Service]
Type=oneshot
ExecStart=/usr/bin/systemctl reboot
```
reboot-timer.j2

```
[Unit]
Description=Schedule reboot at a specific time if updates require a reboot

[Timer]
OnCalendar=*-*-* {{ reboot_time|default("02:00") }}
Persistent=true

[Install]
WantedBy=timers.target
```

2024-08-30 12:10 UTC, konstruktoid requested changes

2024-08-30 12:10 UTC, konstruktoid commented on README.md
> +`reboot_time_margin_mins` to avoid overloading hypervisors.
You should probably note that this is currently only supported on Debian-family distributions.

2024-08-31 06:15 UTC, konstruktoid approved these changes

2024-08-31 06:15 UTC, merged

2024-08-31 06:16 UTC, konstruktoid commented
Thanks @jdaln!